---
- name: (Red Hat/SLES OSs) Add NGINX signing key
  ansible.builtin.rpm_key:
    fingerprint: 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62
    key: "{{ keysite }}"
  when: ansible_facts['os_family'] in ['RedHat', 'Suse']
